apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "url-shortener.api" . }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.api.strategy.type }}
    {{- if (eq "RollingUpdate" .Values.api.strategy.type) }}
    rollingUpdate:
      maxUnavailable: {{ .Values.api.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.api.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "url-shortener.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "url-shortener.selectorLabels" . | nindent 8 }}
        component: api
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "url-shortener.api" . }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containers.api.port }}
              protocol: TCP
          env:
            - name: API_PORT
              value: {{ .Values.api.containers.api.port | quote }}
            - name: BASE_URL_FOR_SHORT_URL
              value: {{ .Values.ingress.host }}
            - name: SQLALCHEMY_DATABASE_URI
              value: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@url-shortener-postgresql.url-shortener.svc.cluster.local:5432/{{ .Values.postgresql.auth.database }}"
            - name: SQLALCHEMY_TRACK_MODIFICATIONS
              value: "false"
            - name: AUTHENTICATOR_PORT
              value: {{ .Values.authenticator.service.port | quote }}
            - name: AUTHENTICATOR_ENDPOINT
              value: us-authenticator.url-shortener.svc.cluster.local
          {{- if .Values.api.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}