apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.api" . }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "url-shortener.selectorLabels" . | nindent 4 }}
    component: api
